### ISSUE TITLE
How to run tests and/or examples?

### ISSUE THREAD

**Issue by javadba** [intel-analytics/TopicModeling#10]
There is not any "src/test" directory. Also there is no documentation how to run the LDAExample (or any docs at all actually).  Is there a blog or information somewhere?

**Comment by hhbyyh** [comment]
OnlineLDA has been merged into Spark MLlib, Please refer to http://spark.apache.org/docs/latest/mllib-clustering.html#latent-dirichlet-allocation-lda for usage
