### ISSUE TITLE
Output NaN when print perplexity 

### ISSUE THREAD

**Issue by rql123** [intel-analytics/TopicModeling#7]
When training LDA with these parameters below, the perplexity value is NaN.

output:
Perplexity of 2-th is 1.5110028503504283
Perplexity of 3-th is 1.4966084893101157
Perplexity of 4-th is 1.4418085535706147
Perplexity of 5-th is NaN

para:
--driver-memory 50G
--executor-memory 100G
--total-executor-cores 100
workers: 100
partitions: 200
topic num: 1M
doc: 2.3M
vocabulary: 500K
iterator: 50

LiuQing

**Comment by dding3** [comment]
The root cause is results for two huge positive integer multiplication exceeds Integer.MAX and get a negative number(docTopicCOunter(topic)*termTopicCounter(topic) here), when calculate Math.log of the negative number, we get a NaN. We adjusted order of the calculation and fix the issue.
